defaults:
  - _self_
  - dataset: terraces_aniso_ladzany_128_32
  - model: deeplabv3/resnet101
  - paths: default

# Inference settings
checkpoint_path: null
batch_size: 64
num_workers: 8

# Hydra overrides
hydra:
  run:
    dir: ${paths.output_dir}/evaluation/${now:%Y-%m-%d}/${now:%H-%M-%S}
