_target_: datasets.dataset.TerassesSegmentationDataset
data_path:
  ladzany: "${paths.data_dir}/terrases/ISO(ladzany)_1.npz"
  sasovske: "${paths.data_dir}/terrases/ISO(sasovske)_1.npz"
  sitno: "${paths.data_dir}/terrases/ISO(sitno)_1.npz"
  tribec: "${paths.data_dir}/terrases/ISO(tribec).npz"
manifest_path: "${paths.data_dir}/terrases/master_manifest.parquet"
subset: "full"
held_out_location: "sitno"
full_location: "tribec"
pos_only: false
min_valid_fraction: 0.0
use_soft_mask: false
